baseURL = 'https://mayaflux.org/'
languageCode = 'en-us'
title = 'MayaFlux'
theme = 'mayaflux-minimal'

[params]
description = "Digital-First Multimedia Computation Framework"

[params.homeInfoParams]
Title = "MayaFlux"
Content = "Revolutionary C++20 multimedia DSP framework - digital-first paradigms for audio, visual, and control data"

[[menu.main]]
name = "Download"
url = "/download/"
weight = 1

[[menu.main]]
name = "Personas"
url = "/personas/"
weight = 2

[[menu.main]]
name = "Onboarding"
url = "/onboarding/"
weight = 3

[[menu.main]]
name = "Tutorials"
url = "/tutorials/"
weight = 4

[[menu.main]]
name = "Docs"
url = "https://mayaflux.github.io/MayaFlux/"
weight = 5

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
